# Generated by Django 3.1 on 2020-08-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestatechange",
            name="game",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_changes",
                to="games.game",
            ),
            preserve_default=False,
        ),
    ]
